(define (interval-sign x)
  (cond ((and (>= (upper-bound i) 0)
              (>= (lower-bound i) 0))
         1)
        ((and (< (upper-bound i) 0)
              (< (lower-bound i) 0))
         -1)
        (else 0)))

(define (mul-interval x y)
  (cond ((> (interval-sign x) 0)
         (cond ((> (interval-sign y) 0)
                (make-interval (* (lower-bound x)
                                  (lower-bound y))
                               (* (upper-bound x)
                                  (upper-bound y))))
               ((< (interval-sign y) 0)
                (make-interval (* (upper-bound x)
                                  (lower-bound y))
                               (* (lower-bound x)
                                  (upper-bound y))))
               (else
                (make-interval (* (upper-bound x)
                                  (lower-bound y))
                               (* (upper-bound x)
                                  (upper-bound y))))))
        ((< (interval-sign x) 0)
         (cond ((> (interval-sign y) 0)
                (make-interval (* (lower-bound x)
                                  (upper-bound y))
                               (* (upper-bound x)
                                  (lower-bound y))))
               ((< (interval-sign y) 0)
                (make-interval (* (upper-bound x)
                                  (upper-bound y))
                               (* (lower-bound x)
                                  (lower-bound y))))
               (else
                (make-interval (* (lower-bound x)
                                  (upper-bound y))
                               (* (lower-bound x)
                                  (lower-bound y))))))
        (else
         (cond ((> (interval-sign y) 0)
                (make-interval (* (lower-bound x)
                                  (upper-bound y))
                               (* (upper-bound x)
                                  (upper-bound y))))
               ((< (interval-sign y) 0)
                (make-interval (* (upper-bound x)
                                  (lower-bound y))
                               (* (lower-bound x)
                                  (lower-bound y))))
               (else
                (make-interval (min (* (lower-bound x)
                                       (lower-bound y))
                                    (* (upper-bound x)
                                       (upper-bound y)))
                               (max (* (upper-bound x)
                                       (lower-bound y))
                                    (* (lower-bound x)
                                       (upper-bound y)))))))))
